# Setup
title: "Orphan Open Source Software"
description: "Open source software abounded by maintainers"

# About/contact
author:
  name: "≈Åukasz Lenart"
  url: "https://lenart.org.pl"

#Others
markdown: kramdown

theme: jekyll-theme-hacker
